### ISSUE TITLE
Tester required for Mac-OS

### ISSUE THREAD

**Issue by aplteam** [aplteam/Tatin#1]
Currently neither the Client nor the Server has been tested under Mac-OS.

I have no Mac, so a volunteer is required.

**Comment by aplteam** [comment]
Amazon does not offer Mac-OS instances

**Comment by mkromberg** [comment]
I'm testing Tatin 0.17 under Big Sur. Having a few problems that I suggest we communicate directly about using via e-mail, and post back here when we have it all sorted.

**Comment by aplteam** [comment]
Will be closed as soon as these problems are fixed.

**Comment by aplteam** [comment]
@Gil: can we close this?
