### ISSUE TITLE
Automatic update of tatin client only updates tatin in the usual default directory and not where it could have been moved

### ISSUE THREAD

**Issue by dyavc** [aplteam/Tatin#106]
PREP:
In Dyalog, change your user  CommandFolder from [HOME]\MyUCMDs to a custom location like
C:\Users\Alpha\Documents\dyalogv182u64\MyUCMDs

There, install an older version of Tatin client such as 0.78.2.+1203 from 17 Oct.

REPRO:
     ]tatin.version
 Tatin  0.78.2+1203  2022-10-17 
      ]tatin.init
User settings re-established in ⎕SE._Tatin.Client from C:\Users\vince\AppData\Roaming\Tatin\tatin-client.json
      ]tatin.listpackages

You are using an outdated version of the Tatin client.
Would you like to update automatically? (Y/n) Y
⎕SE._Tatin.RumbaLean.[LIB]

Rebuilding user command cache... done
130 commands reloaded
Tatin updated: 0.79.1+1234 from 2022-10-31
* Command Execution Failed: Tatin client updated to 0.79.1+1234; please execute the last Tatin user command again

Only the usual default location of C:\users\<your name here>\Documents\MyUCMDs has been updated.

**Comment by aplteam** [comment]
Changed in 0.79.2
