### ISSUE TITLE
BuildPackage - when specifying version explicitly, don't auto bump build number

### ISSUE THREAD

**Issue by e9gille** [aplteam/Tatin#122]
If specifying the version when building a package, I expect that version to be honoured and don't want it to automatically try to increment the build number. As it is, I get a build number which doesn't match my build version in the release pipeline.

**Comment by aplteam** [comment]
To clarify, you would be okay with `BuildPackage` bumping the build number in case the version number is passed as an argument does not carry a build number, but if a build number is specified then it should be accepted and not bumped, correct?

**Comment by e9gille** [comment]
Yes, that's correct.
Essentially, in my scenario, I don't commit any changes after building and publishing a package, so the autobump causes an off by one build number.

**Comment by aplteam** [comment]
Changed in 0.91.0
