### ISSUE TITLE
BuildPackage - build number not recognised properly

### ISSUE THREAD

**Issue by e9gille** [aplteam/Tatin#123]
If specifying the build number using a third dot rather than a plus (e.g. `1.2.3.4`), it is recognised correctly by the `Registry.SplitVersionFromBuild` but not by `Client.BuildPackage`, which appends the build number from the config file (which seems to default to `+1`).

**Comment by aplteam** [comment]
Using the dot as a separator was marked as deprecated for several months. Recently this was, as announced, removed. 

The documentation states that the build number must be separated from the version number by a `+` character.

The comments in `Registry.SplitVersionFromBuild` do not mention the dot as a separator any more.

Is there a really compelling reason to keep supporting the dot as a separator? (I hope not)
