### ISSUE TITLE
Support for proxy server

### ISSUE THREAD

**Issue by e9gille** [aplteam/Tatin#124]
Sitting behind a corporate firewall where we need to use a proxy server to access external sites makes it impossible to use public packages from tatin.dev.
Having investigated the issue I found that for our scenario, where the proxy server is using http (non-secure), and the endpoint is using https (tatin.dev), one would need to upgrade the tcp connection to the proxy server after it has been established. This is currently not supported by Conga.
At the moment we have to modify the Tatin client by replacing the http calls with .NET tools, which isn't great.

**Comment by e9gille** [comment]
To clarify, Tatin has no support for proxy at all at the moment, but even if it was added, it couldn't cater for our scenario without the use of .NET tools.

**Comment by e9gille** [comment]
To be honest, in the read-only scenario maybe so, but we need to use secure channels in all communication, so that wouldn't be accepted.

**Comment by e9gille** [comment]
Found out from Dyalog that support for this was added, but not announced. I created a draft PR in RumbaLean with the new feature outlined and once that is completed and added we can look at using that in Tatin to make it configurable.

In my scenario I would need to specify a proxy server per registry, as internal servers should not go via proxy.

**Comment by aplteam** [comment]
Implemented in 0.95.0

**Comment by e9gille** [comment]
I can't see that this has been implemented yet, although the underlying tools should support it.
I'll see what I can do.
