### ISSUE TITLE
UpdateTatin fails if latest available release version has minor version 100 or more.

### ISSUE THREAD

**Issue by e9gille** [aplteam/Tatin#140]

**Comment by aplteam** [comment]
Fixed in v0.100.1

But the next update must be performed manually I am afraid. 

If you really don't want that then follow this recipe:

1. Set a stop on `⎕SE._Tatin.Client.UpdateClient[22]*`
2. Execute `]Tatin.UpdateTatin`
3. When you reach the stop execute `→⎕LC+3`

That will update Tatin.
