### ISSUE TITLE
uninstallpackage deleted much too much

### ISSUE THREAD

**Issue by kdtp** [aplteam/Tatin#145]
I am sure, I did wrong somewhere. But nevertheless I like to let you, that uninstallpackage can easily delete your whole user profile/home.

I installed like
]Tatin.InstallPackage httpcommand
sucessfully but in the wrong folder namely my /Users/xxxxx on my Mac.

than I gave a try to
]Tatin.UnInstallPackage httpcommand

resulting in my home folder emptied (besides those files where permissions are lacking).

So just two commands can let to disaster.

**Comment by aplteam** [comment]
Fixed in 0.100.2

Now it checks whether the installation folder is empty apart from Tatin's own two files `apl-buildlist.json` and `apl-dependencies.txt`. Only if that's the case the folder is removed.
