### ISSUE TITLE
What is going to happen to www.tatin.dev?

### ISSUE THREAD

**Issue by aplteam** [aplteam/Tatin#15]
Currently that directs tom tatin.dev

**Comment by abrudz** [comment]
Sounds like the right thing to me.

**Comment by aplteam** [comment]
Well, it could instead be the place to provide information about Tatin, including how to use it etc.

That would certainly make sense as well, and keeping it separate from https://tatin.dev would make it easier to maintain.

**Comment by abrudz** [comment]
No, please do not make the result of typing `www.tatin.dev` and `tatin.dev` into your browser give different results! Browsers and other tools will often automatically insert or hide `www`.

Also, I doubt you can point to any modern and maintained site where the presence or absence of `www` makes a substantial difference.

**Comment by aplteam** [comment]
>
> No, please do not make the result of typing www.tatin.dev and tatin.dev
> into your browser give different results! Browsers and other tools will
> often automatically insert or hide www.
>

No, certainly not. No tool and no browser is allowed to tamper with a URL
entered by a user. It's rather the server that returns a different result,
usually as a 301 (Redirect).

**Comment by aplteam** [comment]
Okay, www.tatin.dev is a redirect to tatin.dev
