### ISSUE TITLE
]Tatin.BuildPackage should fail gracefully when .NET Framework not available

### ISSUE THREAD

**Issue by mkromberg** [aplteam/Tatin#151]
]Tatin.BuildPackage should fail gracefully when .NET Framework not available:

DOMAIN ERROR
QuadNEW[7] r←⎕NEW arg
             ∧
      System.Environment.Version
8.0.0

It would be better to state that BuildPackage requires .NET Framework (until this is no longer the case).

**Comment by aplteam** [comment]
Solved in 0.103.0
