### ISSUE TITLE
Suggestion for a page with Package Ideas

### ISSUE THREAD

**Issue by sloorush** [aplteam/Tatin#152]
[Not reporting an issue but a suggestion]

## Idea
A public place where people can note down and pick up ideas of packages that are needed by the community and what packages they can build.

## Users

- People who want to build packages, but do not have any ideas of what might be needed by the community
- People who want a package for something but don't have the time to build one.

## Implementation

- A page on the website (customisable but might lack intuitiveness)
- Pinned GitHub issue (reactions and discussions will be easier)
- GitHub discussions tab is also an excellent option (reactions and discussions are appropriately managed, and tree conversations make it kind of a list too)
- A wiki page (easier to maintain a list)

**Comment by DavinChurch** [comment]
Good idea. I like the GitHub options due to their support, but not everyone has a GitHub account so one of the other options might be more accessible.

**Comment by aplteam** [comment]
I think only the APL wiki and GitHub are practical options. Yes, one needs to have a GitHub account for this, but thanks to spammers the same is true for the APL wiki.

Using GitHub keeps it as close to the project as possible. Putting it on the APL wiki gives us more freedom.

Hmmm...

**Comment by DavinChurch** [comment]
APL Wiki can be read without an account, I'm not sure the same is true of GitHub.

**Comment by sloorush** [comment]
Github public repositories are also readable without an account.

I personally feel github discussions will be a better place than the wiki
because of reaction and discussion capabilities. Also that it stays close
to the project.

**Comment by aplteam** [comment]
Add some information regarding the GitHub discussions of the Tatin project as the best place to discuss packages.

**Comment by sloorush** [comment]
Thanks Kai! Should I set it up or are you happy to do it?

**Comment by aplteam** [comment]
Carry on!

**Comment by sloorush** [comment]
Thanks @aplteam! I have made the discussion. LMK if you would like to change anything. Might be worth it to pin the discussion(I am not sure if it is possible, but it should be).

This issue can be closed if nothing needs to be changed. ^_^
