### ISSUE TITLE
md->html conversion on group homepage does not handle # headers

### ISSUE THREAD

**Issue by mbaas2** [aplteam/Tatin#171]
When editing a group's homepage, it is possible to use Markdown. However, while most md seems to be supported, the # headers are not. Example: https://tatin.dev/v1/group-homepage?name=mbaas

**Comment by aplteam** [comment]
There must be a space between the `#` and the text.

Compare

# With space

with

#Nospace

**Comment by mbaas2** [comment]
Ouch, ofc!  Sorry...🫢

**Comment by aplteam** [comment]
Interesting. Chrome did **not** show the space once, but now it does.

In short, the definition is correct, and something is wrong.

**Comment by aplteam** [comment]
Okay, understood, conflicting actions ;)
