### ISSUE TITLE
Why is the minimum minimumAPLVersion required to be 18.0 or up?

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#176]
I have a package that specifically requires at least v17.0. I know that Tatin can't run on anything less than v18.0, but I'd like people to know that if they've got an older version of Dyalog that they can download the package directly from GitHub to use it without Tatin if they want. Is that not reasonable information to be able to provide?

**Comment by aplteam** [comment]
How do you load the package into the workspace?

**Comment by DavinChurch** [comment]
Without Tatin, just pick up the code directly from GitHub. It is available as source code files, a saved workspace, or a namespace script, however that is preferred. Since it involves no dependencies or other nice facilities that Tatin provides, Tatin is not required to make use of it (if the APL version cannot be updated).

**Comment by aplteam** [comment]
Then it's not a package, and the version of APL is a different matter.

If it's consumed as a package then Tatin is required, and therefore 18.0 is
the minimum version.

**Comment by DavinChurch** [comment]
Very well. I was trying to inform them that it could also be used as a non-package.

**Comment by aplteam** [comment]
That's fine, but not this way, it would defeat the purpose of the property.
