### ISSUE TITLE
Changing a package description?

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#177]
Is there a way to modify an existing package description (to improve its wording) without building a new release?

**Comment by aplteam** [comment]
Nope. You have to release a new version.

**Comment by DavinChurch** [comment]
Thanks. It would be nice to be able to make minor adjustments like that, but I guess that's too difficult.

**Comment by aplteam** [comment]
It's not difficult, but it's difficult to draw the line. What should be allowed, what shouldn't? 

Also, when I download a version and compare the ZIP with the very same version downloaded yesterday, I expect them to be equal, and allowing something like this would make that impossible.
