### ISSUE TITLE
Tatin user command does not work after running ]tatin.updatetatin

### ISSUE THREAD

**Issue by dyavc** [aplteam/Tatin#198]
Tatin user command does not work after running ]tatin.updatetatin

1)  I install Dyalog 19.0.48959 Unicode 64-bit.
2)  ]activate all
)off and restart dyalog
3)  ]tatin.updatetatin

Your version of Tatin is 0.104.1
Latest published version is 0.112.0
Would you like to download and install 0.112.0 ? (Y/n) Y
Tatin successfully updated to version 0.112.0 in C:\Users\[...redacted...]
)off and restart dyalog

4) ⍝  now Tatin does not work
]tatin.version
* Invalid user command; to see a list of all user commands type
      ] -?                                                     

      ]tools.version
 Dyalog  19.0.48959 64-bit Unicode, BuildID abfdd505 
 OS      Windows 11 (10.0.22631) 64-bit              
 Link    4.0.17                                      
 SALT    2.915                                       
 UCMD    2.6                                         
 .NET    .NET Framework 4.8.9241.0                   
 WS      19.0                                        
 Tatin   0.112.0                                     
 Cider   0.39.0

**Comment by aplteam** [comment]
Please try `]Ureset`, that should fix it.

It appears to be a SALT problem: why does SALT not recognize that something has changed, as it should?
