### ISSUE TITLE
PublishPackage "not a folder" message confusing when file not found

### ISSUE THREAD

**Issue by rikedyp** [aplteam/Tatin#206]
I tried
```
]TATIN.PublishPackage g/TinyTest/Dist/RikedyP-TinyTest-1.0.0.zip [tatin]
```
and got
```
Is not a folder: g/TinyTest/Dist/RikedyP-TinyTest-1.0.0.zip
```

However, the issue was that I was already in "g" so it was simply the file was not found. At first I was confused by the message, so if possible it should be changed to reflect the actual issue, since ]PublishPackage allows both folders and .zip files.

**Comment by aplteam** [comment]
Fixed in 0.114.0
