### ISSUE TITLE
Zipping file with spaces in path

### ISSUE THREAD

**Issue by Bombardier-C-Kram** [aplteam/Tatin#208]
ZipArchive needs to surround _filename with double quotes.
E.x.

      'zip ',_filename,' ',tempFilename,' -q' ⍝ This will cause an error 
zip /mnt/c/Users/Holdens Thinkpad/Documents/Dyalog APL-64 19.0 Unicode Files/JWTAPL/Dist/bkaw-JWTAPL-2.1.0.zip /tmp/spacequacker_230219664.tmp -q
      'zip "',_filename,'" ',tempFilename,' -q' ⍝ This will not
zip "/mnt/c/Users/Holdens Thinkpad/Documents/Dyalog APL-64 19.0 Unicode Files/JWTAPL/Dist/bkaw-JWTAPL-2.1.0.zip" /tmp/spacequacker_230219664.tmp -q

**Comment by aplteam** [comment]
Fixed with 0.115.0
