### ISSUE TITLE
ToLower needs updating for version 20.0

### ISSUE THREAD

**Issue by rikedyp** [aplteam/Tatin#210]
Trying to use Tatin in version 20.0 is hitting a lot of issues due to deprecated `819⌶`

```
      ]tatin.updateTatin

Your version of Tatin is 0.112.1
Latest published version is 0.115.0
Would you like to download and install 0.115.0 ? (Y/n) 
4:DOMAIN ERROR: I-Beam function 819 has been withdrawn; use ⎕C instead
ToLower[3] (819⌶)⍵
           ∧
```

With `]udebug on` I find myself in `⎕SE._Tatin.RumbaLean.Core`

```
 ToLower←{
     ⍝ ⍵ ←→ Character Array
     ⍝ ← ←→ Converted to lower case
     (819⌶)⍵
 }
```

Should use `⎕C` with optional `819⌶` as fallback for earlier Dyalog versions, although probably not needed for Tatin.

**Comment by rikedyp** [comment]
Actually, it seems I cannot load packages at all

```
      ]tatin.loadPackages TinyTest
* Command Execution Failed: DOMAIN ERROR
```

**Comment by aplteam** [comment]
Regarding 819⌶: Rumba will be updated soon.

Regarding the DOMAIN ERROR: please update Tatin and try again,

**Comment by aplteam** [comment]
See #201
