### ISSUE TITLE
BuildPackage should include interface files (*.apli)

### ISSUE THREAD

**Issue by e9gille** [aplteam/Tatin#211]
I had overlooked that BuildPackage has an implicit filter. At the moment it is just missing the interface files out of the standard set of extensions. I have to ponder if this may cause other issues, but presumably there's a reason to apply a filter. Care to share?

https://github.com/aplteam/Tatin/blob/914b181d71e3bc5e59ec345a8ba053eb0158031a/APLSource/Client/GetAllFiles.aplf#L15

**Comment by aplteam** [comment]
That `.apli` is missing is an oversight.

I added the filter without much thought; it just felt right to ensure that it only adds APL source files and nothing else since other files should be handled differently.

Are you proposing to remove the filter altogether?

**Comment by e9gille** [comment]
That's what I'm proposing, yes, but I need to think about the scenarios first. For now, just add the `.apli` extension to the list.

**Comment by aplteam** [comment]
Fixed in 0.115.1
