### ISSUE TITLE
HTML Base tag causes problems

### ISSUE THREAD

**Issue by aplteam** [aplteam/Tatin#29]
Since 0.17.1 the HTML base tag carries a port number in case the Tatin server does not use a standard port (80 or 443).

This is required because otherwise the links in the documentation would not work when one runs a Tatin server on her own machine with a non-standard port.

However, when Tatin is run behind, say, Apache then the port is not a standard one but must not be assigned to the HTML base tag anyway, because Apache will most probably use a standard port.

**Comment by mkromberg** [comment]
In general, I think any server needs a configuration parameter which tells it how it is being exposed to the outside world. It might be inside a container on an unsecured port, think it is http://localhost:8088, but to the outside work be exposed as a secure server on a standard port, e.g. https://tatin.dev.

**Comment by aplteam** [comment]
Fixed. New INI entry `[CONFIG]BaseTagPort` introduced that defaults to 0: no port added to the HTML base tag.
