### ISSUE TITLE
Unable to load conga32_64.so

### ISSUE THREAD

**Issue by YsHaNgM** [aplteam/Tatin#33]
I am using Linux source build, I did installation suggested by documentation. Although when I run `]tatin.publish` it can not load conga32_64.so from tatin installation path (MyUCMDs). It searches for it in my apl path "/home/[myuser]/svn/trunk/apl/" but I have conga33_64.so, then cause "Command Execution Failed".

**Comment by aplteam** [comment]
Will be fixed in the next version of Tatin
