### ISSUE TITLE
Make usage data available to package authors

### ISSUE THREAD

**Issue by aplteam** [aplteam/Tatin#40]
The ideas is to filter what might be of interest to package authors, for example how many times a package was downloaded etc.

Naturally this makes sense once more packages are available on the Tatin server. All activities are logged anyway, so it's just about making the data available in one way or another.

**Comment by DavinChurch** [comment]
It occurs to me that usage data probably ought to be publicly available. When I download OS-based programs from various download sites, each one contains a number or previous downloads, and that (popularity) number helps me decide which program I should try out. I think Tatin could use this as a standard part of the ListPackages command, perhaps?

**Comment by aplteam** [comment]
Implemented in 0.71.0
