### ISSUE TITLE
Allow ListVersions without a group name

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#41]
InstallPackage allows a package name to be specified for installation without the group name, assuming that it's unique to the server. However, ListVersions requires a group name in all cases. Shouldn't ListVersions also allow the group name to be elided and have it assumed where the name is unambiguous?

In addition, it also might be reasonable for ListVersions to be extended and show version information for multiple packages that have the same name in multiple groups. It might be useful in identifying which group's package is desired.

**Comment by aplteam** [comment]
Available in 0.53.0
