### ISSUE TITLE
Allow ListPackages to show info_url

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#43]
The short description of each package is useful to determine if a package might be of interest, but it isn't much help in deciding if it would be appropriate for a particular purpose. For that, full documentation (or at least a ReadMe) is needed. Since it's not Tatin's job to provide that, I would like to suggest that a -info switch be added to ListPackages (and perhaps other commands) to display the value of info_url so that the user will easily know where to go for more information on the package.

**Comment by aplteam** [comment]
I am not sure about this. I expected users to use the web interface for this kind of thing. We are planning to make filters available for tags etc. soon. That would give the user a powerful interface, 

Therefore I am not sure.

Anybody else?

**Comment by DavinChurch** [comment]
A web interface would make many things a lot easier, but it's my general rule to allow **everything** in a system to be accomplished using a command line, and then add web interfaces on top of that to make common or complicated things easier.

**Comment by aplteam** [comment]
I don't think it can be justified to put resources into this. In the end, if you need to check at least one of the info_URLs, you would need to copy it into a browser anyway. It is way easier to use the web interface, because there you just have to click on the link.

Instead we should allocate resources to adding a filter to the web interface.

**Comment by DavinChurch** [comment]
Very well, but that doesn't allow us to write our own APL cover functions to process Tatin data in other ways.

**Comment by aplteam** [comment]
You get what you want: I just learned that when one hovers with the mouse over a URL in the session, one can right-click on it and it will take one to that URL in the default browser.  That has escaped me.

**Comment by aplteam** [comment]
Implemented in 0.51.0
