### ISSUE TITLE
Format -date output

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#44]
I would like to suggest that when a command is to display a -date value, that it be formatted using the OS's default date format rather than just showing a raw numeric value. (Such a format might also be allowed to be overridden by UserSettings, too.)

**Comment by aplteam** [comment]
From my point of view the international date formatting is a much better solution to this.

`2020-08-09` leaves no room for interpretation, `3.4.2021` does.

**Comment by DavinChurch** [comment]
First of all, the international style could be misinterpreted by someone whose local style conflicts with it, so there's an opportunity to be confused either way. It is my opinion that formatting the date however they are used to seeing it is likely to cause less confusion everywhere.

**Comment by DavinChurch** [comment]
Secondly, the -date formatting ISN'T currently formatted at 2020-08-09, it's formatted as 20200809.183416, which is why I was asking for more textual formatting in the first place.

**Comment by aplteam** [comment]
The international date format was chosen because it does not interfere with any local rules.

When I click on the package name in the "Major versions of..." list then it is displayed in international date format, so you must refer to a different place?

**Comment by DavinChurch** [comment]
You must be talking about a web interface, which I have not yet seen. I've been talking about the command-line interface which doesn't seem to be formatting in text at all.

**Comment by aplteam** [comment]
Then you probably meant `]ListVersions`.

In the next version this is done.
