### ISSUE TITLE
Allow ListPackages to show only those that have been recently changed

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#45]
It might also be useful for ListPackages (and similar commands) to only show packages that have been published recently. Perhaps this could be accomplished with a switch such as -since that's given a date or a time frame (such as a number of days ago) to restrict the listings. This will be most convenient when the number of packages available is becoming large.

**Comment by aplteam** [comment]
That sounds like a pretty good idea to me.

**Comment by aplteam** [comment]
With v0.52.0 `]ListPackages` now accepts `-since=`. The date can be specified in two different formats:

```
-since=20200501
-since=2020-05-01
```
