### ISSUE TITLE
Deferred publishing

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#48]
I would like to propose a change to the package-publishing procedure. Of concern is the fact that publishing on a primary server never allows anyone to delete a package once it's published. However, I am worried that I will publish something by mistake (either buggy code or on the wrong server) and be unable to correct my mistake, even if I detect it right away.

Therefore, I would like to suggest an alternative. Once a package is published on a server, make it available ONLY to the author for a short period of time, such as one hour. During that time only the author can install/load it (to check for problems) and during that time the author can still delete the package if needed, even if deletions are not normally allowed. After the time limit expires, it is then available to the public and the delete restriction is enforced normally.

**Comment by DavinChurch** [comment]
As an alternative option, instead of setting a fixed time limit, use a command to "finalize" the publishing and make it available. Then the author can test it as a package as much as needed and then release it to the public when it's ready. Again, this is different than simply publishing to a test server at least in the instance where it was mistakenly published to the production server instead of the test server.

**Comment by aplteam** [comment]
Of course you can fix it if you make a mistake: you just publish a new version.

**Comment by DavinChurch** [comment]
But when it wasn't ready to be published at all, and I meant it to go to the test site, that doesn't help at all.

**Comment by aplteam** [comment]
Ok, implemented in 0.55.0
