### ISSUE TITLE
Restricted registry is available when it shouldn't be

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#56]
As I understand it, I should not have access to the [tatin-test-aplteam] alias, but it shows up in my ListRegistries output.

**Comment by aplteam** [comment]
Yes, this must be a hiccup caused by a pretty early version. Just removed
that line from your user settings

Pasted From Dyalog ]userSettings -eedit

allows that.

It would not work anyway because I have changed the credentials since.
