### ISSUE TITLE
Spelling mistake in GetUserHomeFolder

### ISSUE THREAD

**Issue by e9gille** [aplteam/Tatin#60]
https://github.com/aplteam/Tatin/blob/3e4a51339e93c3fa52f36c69670ef76d98f29e15/APLSource/Client/GetUserHomeFolder.aplf#L22

**Comment by aplteam** [comment]
Fixed

**Comment by e9gille** [comment]
Sorry, my bad, it wasn't a typo in the name of the function, but rather a missing space. It should read:
`0≠≢h:F.ExpandPath h,as,d,add        ⍝ mac`
