### ISSUE TITLE
Error with ]ListPackage -info_url 

### ISSUE THREAD

**Issue by mbaas2** [aplteam/Tatin#62]
]TATIN.ListPackages -info_url
--- Select Tatin Registry -------------------------------------------------------------------------------------------------------------------   
  1.  [tatin]  https://tatin.dev/        
  2.  [test]   https://test.tatin.dev /  

Select one item (q=quit) :1
LENGTH ERROR
ListPackages[33] r←'Packages from:'registry⍪r
                                           ∧
      
      ⍴registry
18
      ⍴r
28 3

**Comment by aplteam** [comment]
Fixed in 0.53.1
