### ISSUE TITLE
v 0.53.0 setup.dyalog.removeme refers to non-existent function

### ISSUE THREAD

**Issue by bpbecker** [aplteam/Tatin#63]
The Setup function in setup.dyalog.removeme has the line
      path2Config ⎕SE._Tatin.Admin.InstallClient ⎕SE.Tatin
There is no InstallClient function in the Admin namespace in the Tatin workspace.

The description of the setup.dyalog file in the online documentation properly shows
     path2Config ⎕SE._Tatin.Admin.EstablishClientInQuadSE ⍬

**Comment by aplteam** [comment]
Fixed in 0.53.1
