### ISSUE TITLE
Docs should mention that you must have a valid Registry directory for the server.  Otherwise, get an error upon loading the server workspace.

### ISSUE THREAD

**Issue by dyavc** [aplteam/Tatin#66]
Docs should mention that you must have a valid Registry directory for the server.  Otherwise, get an error upon loading the server workspace.

e.g.
FILE NAME ERROR: D:\cor\kai1927\repro15oct\Registry\Credentials.txt: Unable to create file ("The system cannot
 find the path specified.")
NPUT[17] r←data ⎕NPUT filename
                ∧
      filename
D:\cor\kai1927\repro15oct\Registry\Credentials.txt

**Comment by aplteam** [comment]
The folder should exist. Fixed in 0.54.1
