### ISSUE TITLE
Tatin.Ping should return 1 for file registries if folder exists

### ISSUE THREAD

**Issue by bpbecker** [aplteam/Tatin#73]
It's a bit of a nit, but for consistency and completeness, Tatin.Ping should report a 1 for an existing folder.

**Comment by aplteam** [comment]
I fail to see why it is more consistent when a function that is designed to check whether a server on the Internet is responsive returns a 1 in case an existing folder is passed as an argument.

Instead I am going to add a check whether `⍵` starts with `http[s]://` or is an alias (`[something]`, and that an alias eventually results in `http[s]://`, otherwise DOMAIN ERROR.

**Comment by bpbecker** [comment]
The reason is for consistency.  I envision my development flow to be:

- Develop on a local, file-based registry.  I don't want or need to run a server when I'm developing locally.
- Once I'm happy, migrate the version to an internally-hosted registry
- Once I'm happy with that, migrate to the [tatin] registry

Tatin.Ping should tell me "the registry is available".  It should report a 1 if the folder exists and 0 if it can't be accessed (e.g. network drive being unavailable or I've done something foolish and erased or renamed the folder).

**Comment by aplteam** [comment]
I am not convinced. There is no need to do a `Ping`, for example:

```
      ]publishPackage /mypackages/aplteam-wonderful-0.1.0.zip /Does/Not/Exist
* Command Execution Failed: "[D:\Does/Not/Exist]" is not a Registry
 ```

**Comment by bpbecker** [comment]
What's the harm in making the behavior consistent?

If I have a file-based registry on a network drive (where I can't run a server), I'd prefer to have consistent behavior where I can check for the availability rather than have to handle an error in the file-based case and have Ping tell me in the server-based case.

Ping should answer the question - is this registry available?

**Comment by aplteam** [comment]
Okay, will be done soon
