### ISSUE TITLE
Introduce deprecated packages

### ISSUE THREAD

**Issue by aplteam** [aplteam/Tatin#76]
Every piece of software will eventually become superfluous in one way or another.

When that becomes true for a package, there should be a way to mark it as deprecated since we cannot just delete it if the delete policy is "none" or "beta-only".

Other package management systems allow a flag "deprecated" to be set. For a package to become deprecated a new release needs to be published with that flag set.

The consequences:

1. By default, `ListPackages` should filter them out
2. On the web:
   1. Those packages should be marked
   2. There should be a mechanism to filter them out
3. When a deprecated package is installed or loaded via a user command a warning should be issued
4. API functions _might_ refuse to process such packages unless an optional flag is set

**Comment by DavinChurch** [comment]
Good plan!

**Comment by aplteam** [comment]
Implemented in 0.80.0
