### ISSUE TITLE
Remove dependency on .NET Core on non-Windows platforms

### ISSUE THREAD

**Issue by aplteam** [aplteam/Tatin#86]
Both the Tatin Server and the Tatin Client use .NET just for zipping/unzipping but nothing else.

While Tatin can be sure that .NET is available under Windows, this is different under Linux. Also, .NET Core is version 3.1, and Microsoft has released .NET 5.0 and 6.0 as successors for .NET Core, but Dyalog APL is not compatible with them. Worse, .NET Core is not supported under Ubuntu 22.04. 

Therefore Tatin should use .NET under Windows but `zip` under Linux.

I am lacking the skills to do this on a Mac, but surely there is a tool available for this.

**Comment by DavinChurch** [comment]
I have a suggestion. If that's the only thing that .Net is needed for, why not dispense with using its Zip facilities altogether? Instead, what about packaging a 3rd-party app with Tatin to do the work for you? 7-Zip (www.7-zip.org) comes to mind - it's public domain (on SourceForge) and runs under both Windows and Linux and includes a command-line interface (and maybe a DLL/SO version as well).

Would something like that be worth checking out?

**Comment by aplteam** [comment]
1. Tatin has no means to install something
2. 7-Zip does not run on a Mac last time I checked

There is no need to use the same mechanism on all platforms. I guess that Linux and Mac-OS both come with tools that do the job (I just have no Mac to check), and under Windows using .NET is okay.

**Comment by DavinChurch** [comment]
1. I don't think that 7-Zip needs to install anything, particularly if it's just a DLL.
2. If it runs on Linux then I would expect it to run on the Mac, too, but I can't verify that.
3. If you don't need it to be portable, then that's fine - just do it different ways on different OSes. But it sounded to me like you're having .Net problems (or at least version requirements) in the first place, are you not?

**Comment by aplteam** [comment]
Under Windows I can be certain that .NET is around in any case.

On all other platforms the `zip` tool suggests itself. `⎕SH` is very fast; that tells it from `⎕CMD`...

**Comment by aplteam** [comment]
Solved with 0.67.0
